#!/usr/bin/env python3
"""One-shot: merge crates/mp/tests/*.rs into suite binaries under suites/."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TESTS = ROOT / "crates/mp/tests"
SUITES = TESTS / "suites"
KEEP_TOP = {"scenarios_runner.rs", "common"}


def suite_for(stem: str) -> str:
    rules: list[tuple[str, str]] = [
        ("ac_verify_", "suite_ac_verify"),
        ("fragment_", "suite_fragment"),
        ("milestone_", "suite_milestone"),
        ("complete_", "suite_milestone"),
        ("init_", "suite_init"),
        ("install_", "suite_install"),
        ("make_install_", "suite_install"),
        ("harness_", "suite_install"),
        ("p6_", "suite_install"),
        ("validate_", "suite_validate"),
        ("verify_lint_", "suite_validate"),
        ("verify_field_", "suite_validate"),
        ("gate_", "suite_validate"),
        ("schema_", "suite_validate"),
        ("mini_schema_", "suite_validate"),
        ("review", "suite_review"),
        ("reviews_", "suite_review"),
        ("spec_review", "suite_review"),
        ("agent_", "suite_agent"),
        ("plan_", "suite_plan"),
        ("execution_", "suite_plan"),
        ("session_", "suite_plan"),
        ("path_", "suite_plan"),
        ("workflow_", "suite_plan"),
        ("decompose_", "suite_plan"),
        ("hybrid_session", "suite_plan"),
        ("track_", "suite_track"),
        ("annotation", "suite_annotation"),
        ("changelog_", "suite_changelog"),
        ("step_", "suite_step"),
        ("config_", "suite_config"),
        ("doctor_", "suite_doctor"),
        ("release_", "suite_release"),
        ("note", "suite_note"),
        ("interview_", "suite_interview"),
        ("changelog", "suite_changelog"),
    ]
    for prefix, suite in rules:
        if stem.startswith(prefix) or stem == prefix.rstrip("_"):
            return suite
    if stem.startswith("p") and len(stem) > 2 and stem[1].isdigit():
        return "suite_phase"
    return "suite_misc"


def rewrite_module_body(text: str) -> str:
    text = re.sub(r"^mod common;\s*\n", "", text, flags=re.MULTILINE)
    text = re.sub(r"\buse common::", "use crate::common::", text)
    text = re.sub(r"\bcommon::", "crate::common::", text)
    text = re.sub(r"use crate::crate::common::", "use crate::common::", text)
    return text


def main() -> None:
    SUITES.mkdir(exist_ok=True)
    top_files = sorted(p for p in TESTS.glob("*.rs") if p.name not in KEEP_TOP)
    if any(p.name.startswith("suite_") for p in top_files):
        raise SystemExit("suite_*.rs already present — aborting")

    by_suite: dict[str, list[str]] = {}
    for path in top_files:
        stem = path.stem
        suite = suite_for(stem)
        by_suite.setdefault(suite, []).append(stem)
        dest = SUITES / f"{stem}.rs"
        dest.write_text(rewrite_module_body(path.read_text()), encoding="utf-8")
        path.unlink()

    for suite, stems in sorted(by_suite.items()):
        lines = ["//! Consolidated integration tests — reduces linker invocations.", "", "mod common;", ""]
        for stem in sorted(stems):
            lines.append(f'#[path = "suites/{stem}.rs"]')
            lines.append(f"mod {stem};")
            lines.append("")
        (TESTS / f"{suite}.rs").write_text("\n".join(lines), encoding="utf-8")

    map_path = ROOT / "crates/mp/src/integration_test_map.rs"
    mapping_lines = [
        "//! Legacy integration-test binary names → consolidated suite binaries.",
        "//! Auto-generated by scripts/consolidate-mp-tests.py — do not hand-edit.",
        "",
        "pub static LEGACY_TEST_BINARY_MAP: &[(&str, &str)] = &[",
    ]
    for suite, stems in sorted(by_suite.items()):
        for stem in sorted(stems):
            mapping_lines.append(f'    ("{stem}", "{suite}"),')
    mapping_lines.append("];")
    mapping_lines.append("")
    map_path.write_text("\n".join(mapping_lines), encoding="utf-8")

    total = sum(len(v) for v in by_suite.values())
    print(f"Consolidated {total} files into {len(by_suite)} suite binaries:")
    for suite, stems in sorted(by_suite.items()):
        print(f"  {suite}: {len(stems)} modules")


if __name__ == "__main__":
    main()
